<?php

declare(strict_types=1);

namespace Domains\Shared\Enums;

enum AtomikLogsTypes: string
{
    case MACRO1  = 'MACRO1';  // REQUEST LINE ENTRY

    case OPERATOR_MACRO1  = 'OPERATOR_MACRO1';  // REQUEST LINE ENTRY

    case MACRO2 = 'MACRO2'; // CONFIRM LICENSE

    case OPERATOR_MACRO2 = 'OPERATOR_MACRO2'; // CONFIRM LICENSE

    case MACRO3 = 'MACRO3'; // AUTHORIZE LINE ENTRY

    case MACRO5 = 'MACRO5'; // LOCATION

    case MACRO10 = 'MACRO10'; // END JOURNEY

    case OPERATOR_MACRO10 = 'OPERATOR_MACRO10'; // END JOURNEY

    case MACRO6 = 'MACRO6'; // LOCATION

    case LICENSE_CREATED = 'LICENSE_CREATED';

    case LICENSE_CONFIRMED = 'LICENSE_CONFIRMED';

    case LICENSE_REVOKED = 'LICENSE_REVOKED';

    case LICENSE_REVOKE_REQUEST = 'LICENSE_REVOKE_REQUEST';

    case LICENSE_REVOKE_REJECTED = 'LICENSE_REVOKE_REJECTED';

    case LICENSE_USED = 'LICENSE_USED';

    case LICENSE_REJECTED = 'LICENSE_REJECTED';

    case EMERGENCY_ALERT = 'EMERGENCY_ALERT';

    case COMMUNICATION = 'COMMUNICATION';

    case DRIVER_REQUESTED_JOURNEY_RESTART = 'DRIVER_REQUESTED_JOURNEY_RESTART';

    case OPERATOR_REQUESTED_JOURNEY_RESTART = 'OPERATOR_REQUESTED_JOURNEY_RESTART';

    case DRIVER_SENDS_MACRO1 = 'DRIVER_SENDS_MACRO1';

    case OPERATOR_SENDS_MACRO1 = 'OPERATOR_SENDS_MACRO1';

    case OPERATOR_AUTHORIZES_LINE_ENTRY_REQUEST = 'OPERATOR_AUTHORIZES_LINE_ENTRY_REQUEST';

    case REQUEST_LINE_EXIT = 'REQUEST_LINE_EXIT';

    case OPERATOR_REQUEST_LINE_EXIT = 'OPERATOR_REQUEST_LINE_EXIT';

    case LINE_EXIT_REQUEST_ACCEPTED = 'LINE_EXIT_REQUEST_ACCEPTED';

    case LINE_EXIT_REQUEST_REJECTED = 'LINE_EXIT_REQUEST_REJECTED';

    case DECLINE_LINE_ENTRY_REQUEST = 'DECLINE_LINE_ENTRY_REQUEST';

    case LICENSE_AREA_SECTION_CLEARED = 'LICENSE_AREA_SECTION_CLEARED';

    case DRIVER_OVER_SPEEDING = 'DRIVER_OVER_SPEEDING';

    case DRIVER_IN_UNAUTHORIZED_AREA = 'DRIVER_IN_UNAUTHORIZED_AREA';

    case SPEED_RESTRICTION_ADDED = 'SPEED_RESTRICTION_ADDED';

    case SPEED_RESTRICTION_DELETED = 'SPEED_RESTRICTION_DELETED';

    case SOS_LICENSE_CREATED = 'SOS_LICENSE_CREATED';

    case MARK_AREA_UNDER_MAINTENANCE = 'MARK_AREA_UNDER_MAINTENANCE';
}
