<?php

declare(strict_types=1);

namespace Domains\Shared\Enums;

enum NotificationTypes: string
{
    case JOURNEY_CREATED = 'JOURNEY_CREATED';
    case JOURNEY_EDITED = 'JOURNEY_EDITED';
    case CURRENT_DRIVER_LOCATION = 'CURRENT_DRIVER_LOCATION';

    case REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';

    case LICENSE_CONFIRMED = 'LICENSE_CONFIRMED';

    case LICENSE_REQUEST = 'LICENSE_REQUEST';

    case INSPECTION_SCHEDULE_CREATED = 'INSPECTION_SCHEDULE_CREATED';

    case INSPECTION_SCHEDULE_DEACTIVATED = 'INSPECTION_SCHEDULE_DEACTIVATED';

    case REQUEST_LINE_EXIT = 'REQUEST_LINE_EXIT';

    case LINE_EXIT_REQUEST_ACCEPTED = 'LINE_EXIT_REQUEST_ACCEPTED';

    case LINE_EXIT_REQUEST_REJECTED = 'LINE_EXIT_REQUEST_REJECTED';

    case PANIC_ACKNOWLEDGED = 'PANIC_ACKNOWLEDGED';
}
