<?php

declare(strict_types=1);

namespace Domains\Shared\Enums;

enum NotificationTypes: string
{
    case JOURNEY_CREATED = 'JOURNEY_CREATED';

    case LINE_ENTRY_REQUEST_DECLINED = 'LINE_ENTRY_REQUEST_DECLINED';

    case JOURNEY_EDITED = 'JOURNEY_EDITED';
    case CURRENT_DRIVER_LOCATION = 'CURRENT_DRIVER_LOCATION';

    case REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';

    case LICENSE_REJECTED = 'LICENSE_REJECTED';

    case LICENSE_CONFIRMED = 'LICENSE_CONFIRMED';

    case LICENSE_REQUEST = 'LICENSE_REQUEST';

    case INSPECTION_SCHEDULE_CREATED = 'INSPECTION_SCHEDULE_CREATED';

    case INSPECTION_SCHEDULE_DEACTIVATED = 'INSPECTION_SCHEDULE_DEACTIVATED';

    case REQUEST_LINE_EXIT = 'REQUEST_LINE_EXIT';

    case OPERATOR_REQUEST_LINE_EXIT = 'OPERATOR_REQUEST_LINE_EXIT';

    case LINE_EXIT_REQUEST_ACCEPTED = 'LINE_EXIT_REQUEST_ACCEPTED';

    case LINE_EXIT_REQUEST_REJECTED = 'LINE_EXIT_REQUEST_REJECTED';

    case PANIC_ACKNOWLEDGED = 'PANIC_ACKNOWLEDGED';

    case LICENSE_AREAS_REVOKED = 'LICENSE_AREAS_REVOKED';

    case LICENSE_REVOKE_REQUEST = 'LICENSE_REVOKE_REQUEST';

    case LICENSE_REVOKE_REJECTED = 'LICENSE_REVOKE_REJECTED';

    case DRIVER_OVER_SPEEDING = 'DRIVER_OVER_SPEEDING';
}
