<?php

declare(strict_types=1);

namespace Domains\Shared\Enums;

enum UserTypes: string
{
    case SYSTEM_ADMIN = 'SYSTEM_ADMIN';

    case SUPER_ADMIN  = 'SUPER_ADMIN';

    case PRINCIPLE_ENGINEER = 'PRINCIPLE_ENGINEER'; // CHIEF_CIVIL_ENGINEER
    case SENIOR_ENGINEER = 'SENIOR_ENGINEER'; // REGIONAL_CIVIL_ENGINEER

    case REGIONAL_SENIOR_TRACK_INSPECTOR = 'REGIONAL_SENIOR_TRACK_INSPECTOR'; // REGIONAL_PERMANENT_WAY_INSPECTOR
    case SENIOR_TRACK_INSPECTOR = 'SENIOR_TRACK_INSPECTOR'; // PERMANENT_WAY_INSPECTOR
    case TRACK_INSPECTOR = 'TRACK_INSPECTOR';


    case SENIOR_TRACK_ATTENDANT = 'SENIOR_TRACK_ATTENDANT'; // LEADER OF GANG MEN
    case TRACK_ATTENDANT = 'TRACK_ATTENDANT'; // INSPECTOR


    case OPERATOR_CONTROLLER = 'OPERATOR_CONTROLLER';

    case OPERATOR_CONTROLLER_SUPERVISOR = 'OPERATOR_CONTROLLER_SUPERVISOR';

    case DRIVER = 'DRIVER';

}
