name: Main workflow

on: [push]

jobs:
  linting:
    name: Run static code analysis
    uses: ./.github/workflows/ci-lint.yml
    permissions: # Add permissions for contents: write
      contents: write # This gives the reusable workflow write access to the repository

  tests:
    name: Run tests
    needs: linting
    uses: ./.github/workflows/ci-test.yml
